---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $node
  labels:
    app: $node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $node
  template:
    metadata:
      labels:
        app: $node
    spec:
      containers:
        - name: node
          image: node-consensus
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/data"
              name: $node
          env:
          - name: NODE
            value: $node
          - name: TYPE
            value: $type
      volumes:
        - name: $node
          persistentVolumeClaim:
            claimName: $node
---
apiVersion: v1
kind: Service
metadata:
  name: $node
spec:
  type: NodePort
  selector:
    app: $node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $node
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /data/$node/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi